{% set name = "pandocfilters" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 002b4a555ee4ebc03f8b66307e287fa492e4a77b4ea14d3f934328297bb4939e

build:
  number: 0
  skip: true # [py<34]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - pandocfilters
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python module for writing pandoc filters
  description: |
    Pandoc consists of a set of readers and writers. When converting a document
    from one format to another, text is parsed by a reader into pandoc's
    intermediate representation of the document—an “abstract syntax tree” or
    AST—which is then converted by the writer into the target format.
  dev_url: https://github.com/jgm/pandocfilters
  # the documentation was updated according to pypi.org
  doc_url: https://pandoc.org/filters.html

extra:
  recipe-maintainers:
    - minrk
