travis:
  secure:
    BINSTAR_TOKEN: BgnIqKrbqRqWgn9yxDMu4NqsPKxU/Z7DRu/M/aRQ1QDyxtiQtJaNHGyS45kFU6tdOM6hyYhy+XOE5m1b4wy0FPZbfYvQdfkrN0wgBO98pcqED9T2gFk87JqSwZVLZO7Yuh50L7t57EQW06cKNIZwwAPjdqMJVyS4iKPjt0GnmdK0aCRAX9pGKXmXd/L0z0D6YaARNGlSYTJHdTLoCC85HwijpgOkjSMsQKF4wKu46MmLtyfxMWAkFrO1+6G9ICD0LLNwxJ9rQbAI/jjXL/jTfn0sYGLl6WNAGTcCKuBWImFqVnlaB63hOsLt1kTECpBChVtnxsIi+yoYAol2trRkaqNPzsuz9uTcJsK9vLq3r9xn3wRn9HH0VxyF9Hq9svOeq4x9sMdKl8X71/vUWup3jtzgfY+5rqEmos6LYeZphGtAqTKK8E2OU8o3QTLgqtQnfb1CqTajDLtTFLqOzwRxrn5iees0Vq2fMcu4h8dFVHVz292HBIixkNKQt4lxKIsDkcsKP1zyLQU9trfYSaOQMqW8PCRLKCBvQvXrEzmmm2OtTM4Yk9pUV6xEvKBOoxzZligEl7pGd9IRfuQ8Y1sr0D0aQUpZlGUWvd4lrj/D42JvPLQlKXsLCkTMhMJy5HOVYUvgO4Bce3GiRzgvoGji8cF71CnN0fS/QAwzTJJAb8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
